### ISSUE TITLE
Gradle sync error, Failed to Resolve com.vdopia.ads.lw:baidu-adapter:1.0.7

### ISSUE THREAD

**Issue by codinghaven** [chocolateplatform/cocos2dx-cpp-android-sample#1]
Using the sample project I'm getting 4 of these type of errors:

ERROR: Failed to resolve: com.vdopia.ads.lw:baidu-adapter:1.0.7
ERROR: Failed to resolve: com.vdopia.ads.lw:chartboost-adapter:1.0.8
ERROR: Failed to resolve: com.vdopia.ads.lw:ogury-adapter:1.0.6
ERROR: Failed to resolve: com.vdopia.ads.lw:youappi-adapter:1.0.8

**Comment by kkawai** [comment]
Ah.... sorry my bad...
easy:  just remove those lines as we don't support those anymore...

**Comment by kkawai** [comment]
Meaning, we don't support baidu, chartboost, ogury, or youappi.   That
sample is very old, too.  I would modify and sample's build.gradle and
AndroidManifest.xml per the following documents:
https://chocolateplatform.com/android/?app_dev_framework=android
<https://chocolateplatform.com/android/?app_dev_framework=android&ad_unit=rewarded&sdk_type=android-rewarded-full>

**Comment by kkawai** [comment]
Hi, I went ahead and updated build.gradle and AndroidManifest.xml in the
sample.  Thanks for checking it out.  Let me know if you have other
questions.  Sorry, I hadn't updated it in forever.

**Comment by codinghaven** [comment]
Everything syncs normally, thanks!
