### ISSUE TITLE
API is not designed well

### ISSUE THREAD

**Issue by codinghaven** [chocolateplatform/cocos2dx-cpp-android-sample#2]
The Vdopia_JNI_Interstitial.cpp source file is not designed well at all.

First I have to use `HelloWorld` as the name of my scene.

The call back interface isn't dynamic, it's hard to understand as there is no language usage
just a bunch of casts.

Suggestion:
1) Create a separate call back interface for all ad types
2) And compose that as a pointer in the Vdopia_JNI_Interstitial.h class

Like this actual design patterns are being used :)

I will create a pull request it's not so hard to fix.

**Comment by kkawai** [comment]
Sounds great.  I agree; the JNI is really badly designed.  It's merely a
way to show that we can call into our ads sdk.  So, please, if there is a
better way...
